### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by Asendaushoe** [hicode002/studentpad-hack#1]
发一下parted和提取的镜像，指令和文件位置可以的话也发一下

**Comment by kasnria001** [comment]
I will give you permission to edit this repo.I am not at home .

**Comment by Asendaushoe** [comment]
……还没发过来啊……，镜像太大的话放网盘也行

**Comment by kasnria001** [comment]
> ……还没发过来啊……，镜像太大的话放网盘也行

I will start now.
no userdata.img

**Comment by kasnria001** [comment]
> ……还没发过来啊……，镜像太大的话放网盘也行

OK

**Comment by o81018o** [comment]
已经证实，平板的严重错误（砖）确由dfs分区更改所致

**Comment by Asendaushoe** [comment]
已经证实，平板的致命错误确由dts分区更改所致

**Comment by o81018o** [comment]
目前平板已恢复正常

**Comment by Asendaushoe** [comment]
我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗

**Comment by Asendaushoe** [comment]
还有parted，mkpart指令中起始地址和终止地址的单位是比特还是字节或是其他？

**Comment by kasnria001** [comment]
> 还有parted，mkpart指令中起始地址和终止地址的单位是比特还是字节或是其他？

B,kb,mb,gb ,all of them are ok.But to make sure the partition size fits the real size of the  partition in emmc  , please use B(Byte) .
for example ,type 14345B.

And start and end sector both need to use B.

**Comment by kasnria001** [comment]
> 我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗
If you want to use C923 iflytek system,follow this guide.
First ,make sure that your data partition is f2fs.
use make_f2fs to format it!

And you need hw_init.

Because all iflytek's softwares are in it.

**Comment by kasnria001** [comment]
> 我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗

If you want to use C00 normal system,you can follow this guide.
flash the C00 's ramdisk ,because the init file in ramdisk seems different in C923 and C00.

Next,I think it is the most important reason. In version and product partition,iflytek use xml and txt file to disable the startup guide and origin desktop.So you can flash C00's version and product or just erase version and product.

You can also edit the version and product partitions,delete all txt such as DelApkList.txt ,and copy cust's InstallApkList.txt,and edit xml files to edit settings.

**Comment by kasnria001** [comment]
Can you put up another issue to describe your problem?

And add titles like ProblemXX--ORIGIN_OS/NORMAL_OS/FLASH_PROBLEM/BRICK_PROBLEM/OTHER_PROBLEM

XX is the number of the problem.

**Comment by Asendaushoe** [comment]
> > 我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗
> > If you want to use C923 iflytek system,follow this guide.
> > First ,make sure that your data partition is f2fs.
> > use make_f2fs to format it!
> 
> And you need hw_init.
> 
> Because all iflytek's softwares are in it.

但缺少这个文件夹会导致无法启动吗，我已确认分区是f2fs文件系统，并已将其格式化，系统启动时自动重建了这个分区但依然是黑屏的状态，如果可以的话希望能上传这个文件夹，或者上传一个可以正常启动的userdata镜像，正常系统似乎无法使用声音相关的功能，连接蓝牙耳机会让系统运行极其迟缓，并且应用程序崩溃

**Comment by Asendaushoe** [comment]
> > 我修改了分区挂点，删除了分区加密，并清除了数据分区，系统也启动了数据分区，然而系统仍然加载了黑屏，因为是用户hw_init
> 
> 如果你想使用 C00 普通系统，你可以按照这个指南。 刷入 C00 的 ramdisk，因为 ramdisk 中的 init 文件在 C923 和 C00 中似乎不同。
> 
> 其次，我认为这是最重要的原因。在版本和产品分区中，科大讯飞使用xml和txt文件来禁用启动指南和原始桌面，这样你可以刷C00的版本和产品，或者只是擦除版本和产品。
> 
> 您还可以编辑版本和产品分区，删除所有txt如DelApkList.txt，并复制cust的InstallApkList.txt，并编辑xml文件以编辑设置。

我用你发过来的dts和vendor按上面所说刷入C00的个别分区，启动后依然没有声音

**Comment by kasnria001** [comment]
> > > 我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗
> > > If you want to use C923 iflytek system,follow this guide.
> > > First ,make sure that your data partition is f2fs.
> > > use make_f2fs to format it!
> > 
> > 
> > And you need hw_init.
> > Because all iflytek's softwares are in it.
> 
> 但缺少这个文件夹会导致无法启动吗，我已确认分区是f2fs文件系统，并已将其格式化，系统启动时自动重建了这个分区但依然是黑屏的状态，如果可以的话希望能上传这个文件夹，或者上传一个可以正常启动的userdata镜像，正常系统似乎无法使用声音相关的功能，连接蓝牙耳机会让系统运行极其迟缓，并且应用程序崩溃

You need hw_init to start iflytek C923 system.

But I can't give you now.

Give me some days.

Because I am concentrating on a big project that install postmarketos(linux) on bzt-w09

**Comment by kasnria001** [comment]
> > > 我修改了分区挂载点，去除了分区加密，并清除了data分区，系统也重建了data分区，然而系统启动时仍然黑屏，是因为缺少hw_init吗
> > > If you want to use C923 iflytek system,follow this guide.
> > > First ,make sure that your data partition is f2fs.
> > > use make_f2fs to format it!
> > 
> > 
> > And you need hw_init.
> > Because all iflytek's softwares are in it.
> 
> 但缺少这个文件夹会导致无法启动吗，我已确认分区是f2fs文件系统，并已将其格式化，系统启动时自动重建了这个分区但依然是黑屏的状态，如果可以的话希望能上传这个文件夹，或者上传一个可以正常启动的userdata镜像，正常系统似乎无法使用声音相关的功能，连接蓝牙耳机会让系统运行极其迟缓，并且应用程序崩溃

Look！My new docs!

**Comment by Asendaushoe** [comment]
我刷入了lineageOS的GSI，虽然依然无法播放声音，但通过蓝牙耳机已经能够正常使用音频功能

**Comment by Asendaushoe** [comment]
希望能尽快上传hw_init，还有那个710是可以解锁的，我在你的说明中补充了

**Comment by kasnria001** [comment]
> 希望能尽快上传hw_init，还有那个710是可以解锁的，我在你的说明中补充了

How to unlock Kirin710?

It can't be unlocked by potatoNV

You mean using DC-unlocker or board software?

**Comment by Asendaushoe** [comment]
用IDT，我将上传这个压缩包

**Comment by kasnria001** [comment]
> 希望能尽快上传hw_init，还有那个710是可以解锁的，我在你的说明中补充了

OK.



I have uploaded it.

Now we can write full docs.

I also mentioned your Chinese guide int this repo.

**Comment by Asendaushoe** [comment]
这套hw_init是旧版的？

**Comment by kasnria001** [comment]
> 这套hw_init是旧版的？

No.It's iflytek BZT-W09's hw_init.

It's the newest.

**Comment by kasnria001** [comment]
> 这套hw_init是旧版的？

So have you try it?

**Comment by Asendaushoe** [comment]
已经放进去了，可是软件版本和用的不太一样？

**Comment by kasnria001** [comment]
> 已经放进去了，可是软件版本和用的不太一样？

Try to connect th  Internet.

It will automatically update.

So can you give me a picture?

**Comment by kasnria001** [comment]
> 已经放进去了，可是软件版本和用的不太一样？

You can use github to upload pictures

**Comment by kasnria001** [comment]
> 已经放进去了，可是软件版本和用的不太一样？

So can you give me an answer?

**Comment by Asendaushoe** [comment]
![IMG_20220816_222727](https://user-images.githubusercontent.com/102898398/184906299-faa4f40d-b792-441d-9bf0-7fe3ccf138e5.jpg)

**Comment by kasnria001** [comment]
> ![IMG_20220816_222727](https://user-images.githubusercontent.com/102898398/184906299-faa4f40d-b792-441d-9bf0-7fe3ccf138e5.jpg)

OK.

There is no problem.

Because when I get my new pad,it is the same.

When your login successfully, It will update.

But the main problem is that you can't login now because the MAC does not  match.

So you can copy the MAC of your device you are using.

**Comment by Asendaushoe** [comment]
我现在登陆上了……好奇怪

**Comment by Asendaushoe** [comment]
更新了ok

**Comment by kasnria001** [comment]
> 更新了ok

Amazing!

So I think iflyek didn't unlink this device.

They just add your new device

**Comment by Asendaushoe** [comment]
或许只是新设备违规所以根本没有绑定？

**Comment by Asendaushoe** [comment]
算了，用的平板还没恢复管控，不整了

**Comment by kasnria001** [comment]
> 或许只是新设备违规所以根本没有绑定？

Maybe.

**Comment by Asendaushoe** [comment]
![IMG_20220816_224527](https://user-images.githubusercontent.com/102898398/184909076-5a19a567-b5da-4a2f-b936-df19779f6e20.jpg)

**Comment by Asendaushoe** [comment]
额，天呐，我账号两台设备都能登陆，同时在线

**Comment by kasnria001** [comment]
> 额，天呐，我账号两台设备都能登陆，同时在线

So iflytek must have some bugs.

But your action will be recorded and sent to iflytek's server

**Comment by Asendaushoe** [comment]
没事，被找也不是第一回了

**Comment by kasnria001** [comment]
> 没事，被找也不是第一回了

I have deleted iflytek's system from my pad.

So I will try  to recover tomorrow.

Then I will post some docs.

And I think we can make dual boot more easily.

We can write a script?

**Comment by kasnria001** [comment]
> > 没事，被找也不是第一回了
> 
> I have deleted iflytek's system from my pad.
> 
> So I will try to recover tomorrow.
> 
> Then I will post some docs.
> 
> And I think we can make dual boot more easily.
> 
> We can write a script?

Or a boot menu?

**Comment by Asendaushoe** [comment]
很难吧，在哪个阶段运行呢？

**Comment by o81018o** [comment]
我先睡了，我妈催我了

**Comment by kasnria001** [comment]
> 很难吧，在哪个阶段运行呢？

maybe in recovery/ramdisk.

Running it in fastboot is too difficult

**Comment by kasnria001** [comment]
I will close this issue now.
Because it is too much.

And It makes my computer too slow.

I will put up a new issue.
