### ISSUE TITLE
Discussions2

### ISSUE THREAD

**Issue by kasnria001** [hicode002/studentpad-hack#4]
Start with this issue!

**Comment by Asendaushoe** [comment]
是在recovery中运行linux的脚本吗

**Comment by Asendaushoe** [comment]
有个问题啊，开机logo怎么是那个花瓣的版本？我分区都刷的你那个版的

**Comment by kasnria001** [comment]
> 是在recovery中运行linux的脚本吗

Yes.

I have achieved it.

But I found very serious problem about dual-booting.

That means our old method has some problems.

FIrst , I have confirmed that iflytek didn't change the product partition.

They just change the version partition.

I have tried it without problem.

Second , modifying fstab.hi6250 to mount sd's version can't be achieved.Because system/vendor/version partition is mounted before fstab.hi6250 works.

That means SD's system will also use emmc's version partition.

But userdata can be remounted in this way.

However , I write a script.

Because version partition is only 32MB.

I can reflash it when I need to switch systems.

**Comment by kasnria001** [comment]
> 有个问题啊，开机logo怎么是那个花瓣的版本？我分区都刷的你那个版的

have you flashed OEMINFO ?

**Comment by Asendaushoe** [comment]
> > 有个问题啊，开机logo怎么是那个花瓣的版本？我分区都刷的你那个版的
> 
> have you flashed OEMINFO ?

刷了

**Comment by o81018o** [comment]
![image](https://user-images.githubusercontent.com/102898398/185117072-22fe1ea2-1bbf-46be-8a9e-6bb6047599b1.png)
前面的几个分区都是已经挂载的是吗

**Comment by o81018o** [comment]
前面几个分区可能在etc/文件夹下的几个文件中挂载，修改是否管用呢？

**Comment by o81018o** [comment]
根目录下似乎也有相关文件

**Comment by o81018o** [comment]
安卓启动分区挂载的资料好像都显示实在init进程里的mount_all函数，它的参数似乎指向/fstab.xxx

**Comment by o81018o** [comment]
你刷过magisk吗，它修改过内核是否可能有影响，就是它自己又挂载了一遍

**Comment by Asendaushoe** [comment]
谷歌的资料显示最初的fstab似乎在ramdisk中，vendor则保存了副本以保证运行：“所有设备都必须将 fstab 文件的副本放到 /vendor/etc 中。这是因为第一阶段 init 在完成分区提前装载之后释放了 ramdisk，并执行了切换根操作，以将位于 /system 的装载移动到了 /。因此，后续任何需要访问 fstab 文件的操作都必须使用 /vendor/etc 中的副本。”

**Comment by Asendaushoe** [comment]
https://source.android.google.cn/devices/architecture/kernel/mounting-partitions-early?hl=zh-cn

**Comment by Asendaushoe** [comment]
“具有启动 ramdisk 的设备必须将 fstab 文件放在启动 ramdisk 根目录中。如果设备同时具有启动 ramdisk 和恢复 ramdisk，就无需对恢复 ramdisk 进行任何更改。”我似乎明白magisk为什么要修补ramdisk了

**Comment by kasnria001** [comment]
> “具有启动 ramdisk 的设备必须将 fstab 文件放在启动 ramdisk 根目录中。如果设备同时具有启动 ramdisk 和恢复 ramdisk，就无需对恢复 ramdisk 进行任何更改。”我似乎明白magisk为什么要修补ramdisk了

However,  there is no fstab in this device's ramdisk.

Remember , Huawei does not follow Android standard strictly.

**Comment by Asendaushoe** [comment]
> > “具有启动 ramdisk 的设备必须将 fstab 文件放在启动 ramdisk 根目录中。如果设备同时具有启动 ramdisk 和恢复 ramdisk，就无需对恢复 ramdisk 进行任何更改。”我似乎明白magisk为什么要修补ramdisk了
> 
> However, there is no fstab in this device's ramdisk.
> 
> Remember , Huawei does not follow Android standard strictly.

好吧，那会在哪里呢

**Comment by o81018o** [comment]
> > “具有启动 ramdisk 的设备必须将 fstab 文件放在启动 ramdisk 根目录中。如果设备同时具有启动 ramdisk 和恢复 ramdisk，就无需对恢复 ramdisk 进行任何更改。”我似乎明白magisk为什么要修补ramdisk了
> 
> However, there is no fstab in this device's ramdisk.
> 
> Remember , Huawei does not follow Android standard strictly.

好吧，那会在哪里呢

**Comment by Asendaushoe** [comment]
会在DTO里吗，“在 Android 9 及更低版本中，设备可以使用[设备树叠加层 (DTO)为提前装载的分区指定 fstab 条目。在 Android 10 及更高版本中，设备必须使用第一阶段 [ramdisk]中的 fstab 文件为提前装载的分区指定 fstab 条目。”

**Comment by kasnria001** [comment]
> 会在DTO里吗，“在 Android 9 及更低版本中，设备可以使用[设备树叠加层 (DTO)为提前装载的分区指定 fstab 条目。在 Android 10 及更高版本中，设备必须使用第一阶段 [ramdisk]中的 fstab 文件为提前装载的分区指定 fstab 条目。”

maybe.

How to extract and modify dto?

**Comment by physics1024** [comment]
Hey bros, we are x1pro hackers. Have you removed the xunfei mdm framework? And there's some codes in service.jar, which create the iptables rules to prevent students from connecting to internet. Though we have already change the system, we still want to know that. We now intend to deal with iclass c6...

**Comment by kasnria001** [comment]
> Hey bros, we are x1pro hackers. Have you removed the xunfei mdm framework? And there's some codes in service.jar, which create the iptables rules to prevent students from connecting to internet. Though we have already change the system, we still want to know that. We now intend to deal with iclass c6...

No，we focus on low level hakcing and programming ,that means we want to hack huawei's fastboot & kernel to dual boot iflytek syetem and normal android system.That means we want to find a common solution for all devices not just iflytek devices
